version: '3'

tasks:
  gen-proto:
    cmds:
      - protoc -I protos/proto protos/proto/sso/*.proto --go_out=./protos/gen/go/ --go_opt=paths=source_relative --go-grpc_out=./protos/gen/go/ --go-grpc_opt=paths=source_relative

  migrate:
    cmds:
      - go run ./cmd/migrator --storage-path=db.sqlite --migrations-path=migrations

  run:
    cmds:
      - go run ./cmd/sso --config=config/config.yml

  test:
    cmds:
      - go test --count 1 ./...
