version: '3'

tasks:
  gen-proto:
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative protos/sso/sso.proto

  migrate:
    cmds:
      - go run ./cmd/migrator --storage-path=internal/storage/sqlite/db.sqlite --migrations-path=internal/storage/sqlite/migrations

  run:
    cmds:
      - go run ./cmd/sso

  test:
    cmds:
      - go test --count 1 ./...
