version: '3'

tasks:
  gen-proto:
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative protos/sso/sso.proto

  run:
    cmds:
      - go run cmd/sso/main.go
